V2 add image update
Moonlight-Panel/Moonlight pull request #424
Opened 2024-06-07 13:12 UTC by Moritz-Deiaco

The Update Feature is doing:
- Updating Information (Name, Author, Startupcmd, ...)
- Updating Variables and docker images (removing unused, updating existent, saving new)

2024-06-07 14:41 UTC, Masu-Baumgartner requested changes
No need to put the HttpClient as a scoped service. Just create an instance and dispose it with the using expression.

using var httpClient = new HttpClient();

2024-06-07 14:43 UTC, Masu-Baumgartner commented
And use FirstOrDefault instead of Any + FindIndex. This reduces the db calls. If the item is missing the return value would be null

2024-06-07 15:06 UTC, Moritz-Deiaco commented
The FindIndex and Any are called on a local list instead of the db

2024-06-07 15:06 UTC, Moritz-Deiaco commented
So it would not really make a difference

2024-06-07 15:18 UTC, Masu-Baumgartner commented
Another thing is that all server using the image need to have their variables updated too as they would stop working if the image varaibles get updated

2024-06-07 15:19 UTC, Moritz-Deiaco commented
Oh, i didnt thought about that, i will do that later/tomorrow

2024-06-07 15:20 UTC, Masu-Baumgartner commented
Oki. Thx for the help with moonlight. Take your time ^^

2025-05-14 18:27 UTC, mxritzdev commented
closed due to not needed anymore

2025-05-14 18:27 UTC, closed without merging